version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: app/frontend/Dockerfile
    
    user: root
    
    ports:
      - "5000:5000"
    
    volumes:
      - ./app/data:/data
    
    environment:
      - PYTHONUNBUFFERED=1
      - BACKEND_API_URL=http://backend:5001
      - AUTH_API_URL=http://auth:5002
    
    env_file:
      - ./app/.env
    
    depends_on:
      - backend
      - auth

  backend:
    build:
      context: .
      dockerfile: app/backend/Dockerfile
    
    user: root
    
    ports:
      - "5001:5001"
    
    volumes:
      - ./app/backend:/backend
      - ./src/mind:/src/mind
      - backend_data:/data
      # - ./app/data:/data
    
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/backend:/src
      - AUTH_API_URL=http://auth:5002
    
    env_file:
      - ./app/.env
    
    depends_on:
      - auth

  auth:
    build:
      context: .
      dockerfile: app/auth/Dockerfile
    
    user: root
    
    ports:
      - "5002:5002"
    
    volumes:
      - ./app/auth:/auth
      - ./app/data/1_users:/auth/data/1_users
    
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://auth_user:auth_pass@db:5432/auth_db
    
    env_file:
      - ./app/.env
    
    depends_on:
      - db

  db:
    image: postgres:15
    
    restart: always
    
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    
    ports:
      - "5432:5432"

volumes:
  auth_db_data:

  backend_data:

  # new_backend:
  #   build: ./app
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - new_frontend
    # volumes:
    #   - ./app:/usr/share/nginx/html

  # mind:
  #   build: ./src
  #   user: root
  #   volumes:
  #     - ./Data:/Data 

  #     - ./Data_old:/Data_old
  #   privileged: true
  #   ports:
  #     - "93:93"
  #   depends_on:
  #     - backend
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   env_file:
  #     ./.env

#now with correct permissions